version: '3.4'

services:
  chefsnacks.web:
    image: ${DOCKER_REGISTRY-}chefsnacksweb
    build:
      context: .
      dockerfile: app/ChefSnacks.Web/Dockerfile
    networks: 
    - chefsnacks_web

networks:
  chefsnacks_web:
    driver: bridge